### ISSUE TITLE
trouble installing v0.6 together with jupyterlab

### ISSUE THREAD

**Issue by mfastudillo** [brightway-lca/bw_temporalis#16] opened 2023-05-12 16:04 UTC
Hi !

if I try `conda install bw_temporalis=0.6 jupyterlab -c cmutel`

I get the following error: 

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libstdcxx-ng conflicts for:
jupyterlab -> python[version='>=3.7'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
bw_temporalis=0.6 -> numpy -> libstdcxx-ng[version='>=10.3.0|>=12|>=9.4.0|>=7.3.0|>=4.9|>=11.2.0|>=7.5.0|>=9.3.0|>=7.2.0']

Package python conflicts for:
jupyterlab -> ipython -> python[version='>=2.7|>=3.8|>=3.9|>=3']
jupyterlab -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.5|>=3.6|>=3.7|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|3.4.*|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.10,<3.11.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__linux==5.15.0=0
  - feature:|@/linux-64::__linux==5.15.0=0
  - jupyterlab -> ipython -> __win

Your installed version is: 5.15.0
```
I have flexible channel priority
@cmutel

**Comment by mfastudillo** [comment] 2023-05-12 16:27
`conda install_bw_temporalis=0.6 -c cmutel` also fails :-/

```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound: 
  - bw_graph_tools[version='>=0.2.2']

```

**Comment by cmutel** [comment] 2023-05-13 07:10
Should be fixed with [new package build](https://anaconda.org/cmutel/bw_graph_tools)

**Closed by cmutel** 2023-05-13 07:10 UTC

**Comment by mfastudillo** [comment] 2023-05-26 11:15
Hi @cmutel 

I tried installing bw_temporalis 0.6 first and then Jupyterlab, I got the following long conflicts ...  
 
[conflicts_bw_temporalis_jupyterlab.log](https://github.com/brightway-lca/bw_temporalis/files/11574573/conflicts_bw_temporalis_jupyterlab.log)

I noticed that bw_graph_tools 0.2.2 got installed instead of 0.2.3

I'd like to be more helpful but the intricacies of conda scape me

**Comment by cmutel** [comment] 2023-05-29 19:21
Python 3.11 doesn't work right now. The problem is that they didn't build it for 3.11 by default, and [by the time that changed](https://github.com/sknetwork-team/scikit-network/pull/558#issuecomment-1540020410) they had updated [`get_shortest_path` API](https://github.com/brightway-lca/bw_graph_tools/blob/main/bw_graph_tools/graph_traversal_utils.py#L32) that I was using, and I don't have the strength to deal with this currently. Use 3.10 and things will work.
